name: Build and publish blog
on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: azure
    env:
      STORYBLOK_TOKEN: ${{ secrets.STORYBLOK_TOKEN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: npm ci

      - name: "Build website"
        run: npm run build

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: "Publish"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "./dist"
